[env:nm_cyd_c5_wifi_test]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.36/platform-espressif32.zip
board = esp32-c5-devkitc-1
framework = arduino
board_build.flash_size = 16MB
board_build.partitions = partitions.csv
monitor_speed = 115200
upload_speed = 230400
upload_port = COM9
monitor_port = COM9

upload_flags =
  --no-stub

lib_deps =
  lvgl/lvgl@8.3.11
  moononournation/GFX Library for Arduino@1.6.6
  https://github.com/pschatzmann/arduino-audio-tools
  https://github.com/pschatzmann/arduino-libhelix.git

build_flags =
  -I include
  -D LV_CONF_INCLUDE_SIMPLE
  -D LV_CONF_PATH=lv_conf.h
  -D ARDUINO_USB_CDC_ON_BOOT=0
  -D ARDUINO_USB_MODE=0
